### ISSUE TITLE
Make the robot ip and port configurable from the CLI 

### ISSUE THREAD

**Issue by show0k** [nbarikipoulos/poppy-robot-client#1]
Users may change the robot hostname, and "poppy.local" is harcoded on the constructor.

**Comment by nbarikipoulos** [comment]
First step done: some connexion context flags have been added to both CLI and script mode:
- --ip for poppy hostname/ip,
- --http-port for http server port,
- --snap-port for snap server port.

In CLI mode, these options are available as other ones,
In the so named 'script mode', adding -h will allow accessing to the help for these new flags, typing:
```shell
node myScript --ip poppy1.local -p 8081
```
will execute myScript.js on robot with poppy1.local as hostname and with a http server configured on port 8081.

**Comment by show0k** [comment]
Great !

**Comment by nbarikipoulos** [comment]
A .poppyrc file has been added in order to persist these configuration values.
Such file could be created uing the CLI command init:
First test the connexion:
```shell
poppy init --ip poppy1.local -p 8081
```
If all is ok (I have added output on console) simply adding a -s flag will create the .poppyrc file.
```shell
poppy init --ip poppy1.local -p 8081 --save
```
Then this .poppyrc file will be use for any launch from this directory.
Note the poppy-robot-client will:
- first check if a .poppyrc file is available, and then extract settings from,
- On a second hand, use the CLI settings if any and then override the corresponding values.
