### ISSUE TITLE
Debug traceback for incorrect usages of CLI

### ISSUE THREAD

**Issue by show0k** [nbarikipoulos/poppy-robot-client#2]
If start an incorrect command like `poppy query`, the help is printed, but also a very long traceback with all internal values.
It begins with
```
{ Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/poppy-robot-client/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/poppy-robot-client/node_modules/axios/lib/core/settle.js:18:12)
```
It is not normal, no ?

**Comment by nbarikipoulos** [comment]
Yes, and no:
The first request always fails due to http server launch on poppy (cf. the end of this [thread](https://forum.poppy-project.org/t/api-rest-poppy-ergo-jr/3516) on  on poppy forum).

To bypass this point, I have created a specific command (cf. documentation):
```shell
poppy init
```
which only wraps a "dummy" rest request to poppy and catch this error.

Once done, the CLI mode will not (or is supposed to) raise any errors...
... excepted if the connexion is lost.

May be it could be a good idea to properly manage a connexion lost case but the result still be here: the first rest request always fails and then the expected action will not be performed.

**Comment by show0k** [comment]
It's my fault. I tested it with a robot without m6 motor (an Ergo Jr with a custom configuration file). The issue is not present with a standard Ergo Jr.
It would have be greater if your lib have been able to works for any Poppy robot (you can retrieve the name of the motors directly from the API), but it needs more work and you don't have any other robot, so...

**Comment by nbarikipoulos** [comment]
But to be able to configure its specific "robot" it is done at least in script mode, but not explained (I will do it later for advanced users):

P.createPoppy() could be called with the following options:
```js
P.createPoppy({
        configFilePath: './config.json',
        connect: { ip: 'MyOtherPoppy.local', port:8080}
})
```
where config.json is the "robot" configuration: the default one used (for poppy-ergo-jr) is located at /config/config.json
About to not discovering the motors, The api request are written, but not used (I keep a "lazy" approach) and deeply accessible via the RawMotorRequest Object which is not "exposed".

Anyway, such  problem persists with the CLI mode where users can not at all pass options to the Poppy object constructor.

The solution will be, as advocated in the issue #1, to manage a local configuration file (a dot rc like one) in order to allow advanced users to use and set their own configurations.

**Comment by nbarikipoulos** [comment]
It slightly digresses from initial purpose: 

So, I'm going to:
- close this issue,
- open one about the finally identified sub-connexion issue with CLI,
- open another one about to ease users to add/use their own robot "configuration" file.
